import re
from playwright.sync_api import Page, expect
from dotenv import load_dotenv
import os
import pytest
from faker import Faker

load_dotenv()

API_URL = os.getenv("API_URL")
fake = Faker()

@pytest.mark.parametrize("url", [API_URL])
def test_example(page: Page, url: str) -> None:
    page.goto(url)
    page.get_by_role("row", name="00.01.02 Kanzlei A CHF 1'850").locator("i").click()
    with page.expect_popup() as page1_info:
        page.get_by_text("Apply").click()
    page1 = page1_info.value
    page1.get_by_text("Start").click()
    page1.locator("li:nth-child(2)").first.click()
    page1.locator("#increment > .fas").first.click()
    page1.locator("div:nth-child(4) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #increment > .fas").click()
    page1.locator("div:nth-child(5) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #increment > .fas").click()
    page1.locator("div:nth-child(6) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #increment").click()
    page1.locator("div:nth-child(7) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #increment > .fas").click()
    page1.locator("div:nth-child(8) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #increment > .fas").click()
    page1.locator("div:nth-child(9) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #increment > .fas").click()
    page1.get_by_role("textbox", name="Please specify").click()
    page1.get_by_role("textbox", name="Please specify").fill(fake.text())
    page1.locator("div:nth-child(12) > .radio-field > .mdt-radio-list > .radio-list > li:nth-child(2)").click()
    page1.locator("div:nth-child(13) > .radio-field > .mdt-radio-list > .radio-list > li:nth-child(2)").click()
    page1.locator("div:nth-child(14) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #increment").click()
    page1.locator("div:nth-child(15) > .radio-field > .mdt-radio-list > .radio-list > li:nth-child(2)").click()
    page1.locator("div:nth-child(16) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #increment > .fas").click()
    page1.locator("div:nth-child(17) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #increment > .fas").click()
    page1.locator("div:nth-child(18) > .radio-field > .mdt-radio-list > .radio-list > li:nth-child(2)").click()
    page1.locator("textarea").click()
    page1.locator("textarea").fill(fake.text())
    page1.get_by_role("textbox", name="Please specify").nth(1).click()
    page1.get_by_role("textbox", name="Please specify").nth(1).fill(fake.text())
    page1.locator("div:nth-child(21) > .radio-field > .mdt-radio-list > .radio-list > li:nth-child(2)").click()
    page1.locator("textarea").nth(1).click()
    page1.locator("textarea").nth(1).fill(fake.text())
    page1.get_by_role("textbox", name="Please specify").nth(2).click()
    page1.get_by_role("textbox", name="Please specify").nth(2).fill(fake.text())
    page1.locator("div:nth-child(24) > .radio-field > .mdt-radio-list > .radio-list > li:nth-child(2)").click()
    page1.locator("textarea").nth(2).click()
    page1.locator("textarea").nth(2).fill(fake.text())
    page1.locator("div:nth-child(26) > .radio-field > .mdt-radio-list > .radio-list > li:nth-child(2)").click()
    page1.locator("div:nth-child(27) > .radio-field > .mdt-radio-list > .radio-list > li:nth-child(2)").click()
    page1.get_by_role("textbox", name="Please specify").nth(3).click()
    page1.get_by_role("textbox", name="Please specify").nth(3).fill(fake.text())
    page1.locator("div:nth-child(29) > .radio-field > .mdt-radio-list > .radio-list > li:nth-child(2)").click()
    page1.get_by_text("Save and next").click()
    page1.get_by_role("textbox", name="Please choose").first.click(button="right")
    page1.locator(".fas").first.click()
    page1.get_by_text("couple household with child").click()
    page1.get_by_role("listitem", name="Yes").first.click()
    page1.locator("div:nth-child(2) > .text-cut").first.click()
    page1.locator("div:nth-child(2) > .text-cut").first.fill(fake.text())
    page1.get_by_role("listitem", name="Yes").nth(1).click()
    page1.locator("div:nth-child(7) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").first.click()
    page1.locator("div:nth-child(7) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").first.fill(fake.text())
    page1.get_by_role("listitem", name="Yes").nth(2).click()
    page1.get_by_role("textbox", name="Please choose").nth(1).click()
    page1.get_by_text("Change in income").click()
    page1.locator("div:nth-child(2) > .input-wrapper > .text-cut").click()
    page1.locator("div:nth-child(2) > .input-wrapper > .text-cut").fill(fake.text())
    page1.locator("div:nth-child(2) > div > div > div:nth-child(4) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page1.locator("div:nth-child(2) > div > div > div:nth-child(4) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill(fake.text())
    page1.get_by_role("listitem", name="Insurance solution").click()
    page1.locator("div:nth-child(3) > .mt-16 > div > .mdt-select > .select-wrapper > .search > .mdt-input").click()
    page1.get_by_text("FirstCaution").click()
    page1.get_by_role("listitem", name="Yes").nth(3).click()
    page1.locator("div:nth-child(6) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page1.locator("div:nth-child(6) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill(fake.text())
    page1.locator("div:nth-child(3) > div > div > div:nth-child(7) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page1.locator("div:nth-child(3) > div > div > div:nth-child(7) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill(fake.text())
    page1.locator("div:nth-child(8) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page1.locator("div:nth-child(8) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill(fake.text())
    page1.locator("div:nth-child(2) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page1.locator("div:nth-child(2) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill(fake.text())
    page1.locator("div:nth-child(2) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").press("Tab")
    page1.locator("textarea").first.fill(fake.text())
    page1.locator("div:nth-child(4) > .mt-16 > div > .mdt-select > .select-wrapper > .search > .mdt-input").click()
    page1.get_by_text("Child tenant").click()
    page1.locator("div:nth-child(5) > .mt-16 > div > .mdt-select > .select-wrapper > .search > .mdt-input").click()
    page1.get_by_text("Caring for relatives in the").click()
    page1.locator("div:nth-child(5) > div > div > div:nth-child(2) > .mt-16 > div > .mdt-select > .select-wrapper > .search > .mdt-input").click()
    page1.get_by_text("Online advertisements").click()
    page1.locator("div:nth-child(5) > div > div > div:nth-child(4) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page1.locator("div:nth-child(5) > div > div > div:nth-child(4) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill(fake.text())
    page1.locator("div:nth-child(5) > div > div > div:nth-child(4) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").press("Tab")
    page1.locator("textarea").nth(1).fill(fake.text())
    page1.get_by_text("Save and next").click()
    page1.locator("i").nth(3).click()
    page1.locator(".text-cut").first.click(button="right")
    page1.locator(".fas").first.click()
    page1.get_by_text("Ms.").click()
    page1.get_by_role("textbox", name="Please specify").first.click()
    page1.get_by_role("textbox", name="Please specify").first.fill(fake.first_name())
    page1.get_by_role("textbox", name="Please specify").nth(1).click()
    page1.get_by_role("textbox", name="Please specify").nth(1).fill(fake.last_name())
    page1.get_by_role("textbox", name="DD.MM.YYYY").first.click()
    page1.get_by_role("cell", name="13").click()
    page1.get_by_role("textbox", name="Please specify").nth(2).click()
    page1.get_by_role("textbox", name="Please specify").nth(2).fill(fake.city())
    page1.locator("div:nth-child(7) > .mt-16 > div > .mdt-select > .select-wrapper > .search > .fas").click()
    page1.get_by_text("in registered partnership").click()
    page1.locator(".mt-16 > .mdt-select > .select-wrapper > .search > .fas").first.click()
    page1.get_by_text("Switzerland", exact=True).click()
    page1.locator("div:nth-child(9) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page1.locator("div:nth-child(9) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill(fake.city())
    page1.get_by_role("textbox", name="DD.MM.YYYY").nth(1).click()
    page1.get_by_role("cell", name="13").click()
    page1.locator("div:nth-child(12) > .mt-16 > div > .mdt-select > .select-wrapper > .search > .fas").click()
    page1.get_by_text("Guarantor").click()
    page1.get_by_role("textbox", name="123 45 67").first.click()
    page1.get_by_role("textbox", name="123 45 67").first.fill(fake.numerify("78 ### ## ##"))
    page1.get_by_role("textbox", name="123 45 67").nth(1).click()
    page1.get_by_role("textbox", name="123 45 67").nth(1).fill(fake.numerify("78 ### ## ##"))
    page1.locator("input[type=\"email\"]").first.click()
    fake_email = fake.email()
    page1.locator("input[type=\"email\"]").first.fill(fake_email)
    page1.locator("input[type=\"email\"]").first.press("Tab")
    page1.locator("input[type=\"email\"]").nth(1).fill(fake_email)
    page1.locator("div:nth-child(3) > div > div > div:nth-child(2) > .mt-16 > div > .mdt-select > .select-wrapper > .search > .fas").click()
    page1.get_by_text("Own home").click()
    page1.locator("div:nth-child(13) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page1.locator("div:nth-child(13) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill(fake.street_address())
    page1.get_by_role("spinbutton").first.click()
    page1.get_by_role("spinbutton").first.fill(fake.postalcode())
    page1.locator("div:nth-child(15) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page1.locator("div:nth-child(15) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill(fake.city())
    page1.locator("div:nth-child(16) > .mt-16 > .mdt-select > .select-wrapper > .search > .fas").click()
    page1.get_by_text("Switzerland", exact=True).click()
    page1.get_by_role("textbox", name="DD.MM.YYYY").nth(2).click()
    page1.get_by_role("cell", name="13").click()
    page1.get_by_role("listitem", name="Yes").first.click()
    page1.get_by_role("listitem", name="Yes").nth(1).click()
    page1.locator("div:nth-child(20) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page1.locator("div:nth-child(20) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill(fake.street_address())
    page1.get_by_role("spinbutton").nth(1).click()
    page1.get_by_role("spinbutton").nth(1).fill(fake.postalcode())
    page1.locator("div:nth-child(22) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page1.locator("div:nth-child(22) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill(fake.postalcode())
    page1.get_by_role("listitem", name="Yes").nth(2).click()
    page1.get_by_role("textbox", name="DD.MM.YYYY").nth(3).click()
    page1.get_by_role("cell", name="13").click()
    page1.locator("div:nth-child(25) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page1.locator("div:nth-child(25) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill(fake.state())
    page1.get_by_role("listitem", name="Yes").nth(3).click()
    page1.locator("div:nth-child(4) > div > div > div:nth-child(3) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page1.locator("div:nth-child(4) > div > div > div:nth-child(3) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill(fake.text())
    page1.locator("div:nth-child(4) > .radio-field > .mdt-radio-list > .radio-list > li:nth-child(2)").click()
    page1.locator("div:nth-child(5) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page1.locator("div:nth-child(5) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill(fake.text())
    page1.locator("div:nth-child(6) > .radio-field > .mdt-radio-list > .radio-list > li:nth-child(2)").click()
    page1.locator("div:nth-child(5) > div > div > div:nth-child(2) > .mt-16 > div > .mdt-select > .select-wrapper > .search > .fas").click()
    page1.get_by_text("Secondary level II").click()
    page1.locator("div:nth-child(3) > .mt-16 > div > .mdt-select > .select-wrapper > .search > .fas").click()
    page1.get_by_text("In education without income").click()
    page1.locator("div:nth-child(16) > .mt-16 > div > .mdt-select > .select-wrapper > .search > .mdt-input").click()
    page1.get_by_text("over CHF 200’").click()
    page1.get_by_role("spinbutton").nth(2).click()
    page1.get_by_role("spinbutton").nth(2).fill(fake.numerify("#####"))
    page1.get_by_role("spinbutton").nth(3).click()
    page1.get_by_role("spinbutton").nth(3).fill(fake.numerify("#####"))
    page1.get_by_role("listitem", name="Excerpt from the debt").click()
    page1.get_by_role("checkbox", name="I hereby confirm that").check()
    page1.get_by_text("Save", exact=True).click()
    page1.wait_for_timeout(1000)
    page1.wait_for_load_state('networkidle')
    page1.locator(".create-child > .container > .fas").click()
    page1.get_by_role("textbox", name="Please specify").first.click()
    page1.get_by_role("textbox", name="Please specify").first.fill(fake.first_name())
    page1.get_by_role("textbox", name="Please specify").nth(1).click()
    page1.get_by_role("textbox", name="Please specify").nth(1).fill(fake.last_name())
    page1.get_by_role("textbox", name="DD.MM.YYYY").click()
    page1.get_by_role("cell", name="13").click()
    page1.locator(".search > .fas").click()
    page1.get_by_text("Switzerland").click()
    page1.locator("#increment i").click()
    page1.get_by_text("Save", exact=True).click()
    page1.wait_for_timeout(1000)
    page1.wait_for_load_state('networkidle')
    page1.get_by_text("Save and next").click()
    page1.wait_for_load_state('networkidle')
    page1.get_by_role("checkbox", name="Should the prospective tenant").check()
    page1.get_by_role("checkbox", name="I confirm that I have").check()
    page1.get_by_role("checkbox", name="I have read the privacy").check()
    page1.get_by_text("Save").click()
